export {default as Home}  from "./Home"
export {default as CaptainLogin}  from "./CaptainLogin"
export {default as CaptainSignup}  from "./CaptainSignup"
export {default as UserLogin}  from "./UserLogin"
export {default as UserSignup}  from "./UserSignup"